name: Packet I/O Tests

# Run tests on PRs, pushes to main, and can be triggered manually
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packet_io/**'
      - '.github/workflows/packet_io_tests.yml'
      - '.github/actions/setup-packet-io/**'
  push:
    branches:
      - main
    paths:
      - 'packet_io/**'
      - '.github/workflows/packet_io_tests.yml'
      - '.github/actions/setup-packet-io/**'
  workflow_dispatch:

# Cancel ongoing runs for PRs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Grant permissions for the workflow
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  packet_io_tests:
    name: Run Packet I/O Tests
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:v0.26.18
      options: '--entrypoint /bin/bash'

    steps:
      # Need to checkout first to use local composite action
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Complete Packet I/O Environment
        uses: ./.github/actions/setup-packet-io
        with:
          zephyr-version: 'v3.7.1'
          setup-python-env: 'true'  # This container needs Python setup
          install-coverage-tools: 'false'

      - name: Run Packet I/O Tests with Twister
        working-directory: zephyr
        shell: bash
        run: |
          source .venv/bin/activate

          # Run all packet_io tests and samples
          python scripts/twister \
            -T ../packet_io/packet_io \
            -p native_sim \
            -v \
            --inline-logs \
            --retry-failed 2 \
            -O twister-out \
            --no-clean

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Packet IO Test Results
          if-no-files-found: ignore
          path: |
            zephyr/twister-out/twister.xml
            zephyr/twister-out/twister.json

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Packet I/O Test Results
          files: "**/twister.xml"
          comment_mode: off