name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
        description: 'Name of the module to test (e.g., flow, weave, register_mapper)'
      module-display-name:
        required: true
        type: string
        description: 'Display name for the module in UI (e.g., "Flow", "Weave", "Register Mapper")'
      test-options:
        required: false
        type: string
        default: ''
        description: 'Additional options to pass to the test script'
      zephyr-version:
        required: false
        type: string
        default: 'v3.7.1'
        description: 'Zephyr version to use'

# Grant permissions for the workflow
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run ${{ inputs.module-display-name }} Tests
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:v0.26.18
      options: '--entrypoint /bin/bash'

    steps:
      # Need to checkout first to use local composite action
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Complete Zephyr Modules Environment
        uses: ./.github/actions/setup-zephyr-modules
        with:
          zephyr-version: ${{ inputs.zephyr-version }}
          setup-python-env: 'true'  # This container needs Python setup
          install-coverage-tools: 'false'

      - name: Run ${{ inputs.module-display-name }} Tests
        shell: bash
        run: |
          cd zephyr_io/..
          ./zephyr_io/scripts/run_tests.sh ${{ inputs.module-name }} ${{ inputs.test-options }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.module-display-name }} Test Results
          if-no-files-found: ignore
          path: |
            twister-out/twister.xml
            twister-out/twister.json

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: ${{ inputs.module-display-name }} Test Results
          files: "**/twister.xml"
          comment_mode: off