name: SwiftIO Tests

# Run tests on PRs, pushes to main, and can be triggered manually
on:
  pull_request:
    branches:
      - main
    paths:
      - 'swift_io/**'
      - '.github/workflows/swift_io_tests.yml'
      - '.github/actions/setup-zephyr-modules/**'
  push:
    branches:
      - main
    paths:
      - 'swift_io/**'
      - '.github/workflows/swift_io_tests.yml'
      - '.github/actions/setup-zephyr-modules/**'
  workflow_dispatch:

# Cancel ongoing runs for PRs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Grant permissions for the workflow
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  swift_io_tests:
    name: Run SwiftIO Tests
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:v0.26.18
      options: '--entrypoint /bin/bash'

    steps:
      # Need to checkout first to use local composite action
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Complete Zephyr Modules Environment
        uses: ./.github/actions/setup-zephyr-modules
        with:
          zephyr-version: 'v3.7.1'
          setup-python-env: 'true'  # This container needs Python setup
          install-coverage-tools: 'false'

      - name: Run SwiftIO Tests
        shell: bash
        run: |
          cd zephyr_io/..
          ./zephyr_io/scripts/run_swift_io_tests.sh

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SwiftIO Test Results
          if-no-files-found: ignore
          path: |
            twister-out/twister.xml
            twister-out/twister.json

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Packet I/O Test Results
          files: "**/twister.xml"
          comment_mode: off